version: '3.8'

services:
  postgres_source1:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: pass1
      POSTGRES_DB: source1
    volumes:
      - ./init-data/00-create-izi.sql:/docker-entrypoint-initdb.d/00-create-izi.sql
    ports:
      - "5434:5432"

  postgres_source2:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: pass2
      POSTGRES_DB: source2
    volumes:
      - ./init-data/00-create-izi.sql:/docker-entrypoint-initdb.d/00-create-izi.sql
    ports:
      - "5435:5432"

  postgres_source3:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: user3
      POSTGRES_PASSWORD: pass3
      POSTGRES_DB: source3
    volumes:
      - ./init-data/00-create-izi.sql:/docker-entrypoint-initdb.d/00-create-izi.sql
    ports:
      - "5436:5432"

  postgres_source4:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: user4
      POSTGRES_PASSWORD: pass4
      POSTGRES_DB: source4
    volumes:
      - ./init-data/00-create-izi.sql:/docker-entrypoint-initdb.d/00-create-izi.sql
    ports:
      - "5437:5432"

  postgres_dwh-en:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: dwhuser-en
      POSTGRES_PASSWORD: dwhpass-en
      POSTGRES_DB: dwh-en
    volumes:
      - ./init-data/dwh-en.sql:/docker-entrypoint-initdb.d/dwh-en.sql
    ports:
      - "5438:5432"

  postgres_dwh-ru:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: dwhuser-ru
      POSTGRES_PASSWORD: dwhpass-ru
      POSTGRES_DB: dwh-ru
    volumes:
      - ./init-data/dwh-ru.sql:/docker-entrypoint-initdb.d/dwh-ru.sql
    ports:
      - "5439:5432"

  airflow:
    image: apache/airflow:latest
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./init-data/dwh-en.sql:/docker-entrypoint-initdb.d/dwh-en.sql
      - ./init-data/dwh-ru.sql:/docker-entrypoint-initdb.d/dwh-ru.sql
      - ./init_airflow_connections.sh:/init_airflow_connections.sh 
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db migrate &&
      /init_airflow_connections.sh &&
      exec airflow standalone"



