services:
  postgres_source1: # тут Main UAE db
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: pass1
      POSTGRES_DB: source1
    volumes:
      - ./init-data/main-en:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"

  postgres_source2: # тут Shop UAE db
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: pass2
      POSTGRES_DB: source2
    volumes:
      - ./init-data/shop-en:/docker-entrypoint-initdb.d
    ports:
      - "5435:5432"

  postgres_source3: # тут Main RU db
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: user3
      POSTGRES_PASSWORD: pass3
      POSTGRES_DB: source3
    volumes:
      - ./init-data/main-ru:/docker-entrypoint-initdb.d
    ports:
      - "5436:5432"

  postgres_source4: # тут Shop UAE db
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: user4
      POSTGRES_PASSWORD: pass4
      POSTGRES_DB: source4
    volumes:
      - ./init-data/shop-ru:/docker-entrypoint-initdb.d
    ports:
      - "5437:5432"

  postgres_dwh-en: # тут итог UAE Main + Shop
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: dwhuser-en
      POSTGRES_PASSWORD: dwhpass-en
      POSTGRES_DB: dwh-en
    volumes:
      - ./init-data/dwh-en.sql:/docker-entrypoint-initdb.d/dwh-en.sql
    ports:
      - "5438:5432"

  postgres_dwh-ru: # тут итог RU Main + Shop
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: dwhuser-ru
      POSTGRES_PASSWORD: dwhpass-ru
      POSTGRES_DB: dwh-ru
    volumes:
      - ./init-data/dwh-ru.sql:/docker-entrypoint-initdb.d/dwh-ru.sql
    ports:
      - "5439:5432"

  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      #- AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT=120
      - AIRFLOW__CORE__PARALLELISM=4
      - AIRFLOW__CORE__DAG_CONCURRENCY=2
      - AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG=2
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./init-data/dwh-en.sql:/docker-entrypoint-initdb.d/dwh-en.sql
      - ./init-data/dwh-ru.sql:/docker-entrypoint-initdb.d/dwh-ru.sql
      - ./init_airflow_connections.sh:/init_airflow_connections.sh
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db migrate &&
      /init_airflow_connections.sh &&
      exec airflow standalone"
